### PR TITLE
Fix scrolling while dragging

### PR DESCRIPTION
**Pull request by blink1073**
Enables scrolling of the viewport while dragging objects within it

### CODE REVIEW

**Comment by sccolbert** [comment]
Do you mean scrolling of the page, or of some particular element?

**Comment by blink1073** [comment]
Dragging a node within its parent node, which is allowed to scroll in its parent.

**Comment by blink1073** [comment]
drag-with-scroll

**Comment by blink1073** [comment]
Confirmed that this works in Chrome and IE, but Firefox doesn't allow scrolling while dragging even when using the native drag n drop.

**Comment by blink1073** [comment]
Better solution is probably to use https://github.com/phosphorjs/phosphor-ui/pull/22 and manually scroll if needed during the drag.

**Comment by sccolbert** [comment]
The problem is detecting whether the user is intending to scroll, or just trying to move the mouse over the item. It's a very subtle problem to determine the user intent here.

**Comment by blink1073** [comment]
Yikes, sounds like a case for a "hot zone" with a timer.

**Comment by blink1073** [comment]
cf https://github.com/jupyter-incubator/dashboards/pull/204/files

**Comment by sccolbert** [comment]
Please open a new discussion issue on the `phosphor` repo.

**Pull request closed without merging**
